version: "2"
services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "80:80"
    networks:
      - my-net  
  backend:
    build:
      context: ./backend
    ports:
      - "5001:5001"
    networks:
      - my-net

networks:
  my-net:
